/*
 * Copyright (C) 2026 PostGraphDB
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
LOAD 'neopostgraph';

SET search_path TO public, pg_catalog, NeoPostGraph;

SELECT FROM edge_in('{"name": "Alice", "age": 30}');

SELECT edge_in('{"name": "Alice", "age": 30}');
SELECT * FROM edge_in('{"name": "Alice", "age": 30}');

--
-- Edge Input Routine
-- NOTE: Never going to be used
--
SELECT edge_in('{}');
SELECT edge_in('{"name": "Alice", "age": 30}');
SELECT edge_in('{"nested": {"a": 1, "b": [2, 3]}}');
SELECT edge_in('{"bool": true, "nullval": null, "float": 3.14}');
SELECT edge_in('{"name": "Bob", "tags": ["dev", "graph"], "scores": [95, 87, 92], "active": true}');

--
-- Edge basic constructor
--
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'));
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'));
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'));
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'));
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'));

--
-- Vertex LTree Label Logic
--
SELECT create_graph('edge_graph', 'public');
SELECT create_elabel('edge_graph', 'person');

SELECT * FROM np_graph graph WHERE graph.name = 'edge_graph';
select * FROM np_edge_label_26;

\d+ np_edge_label_26
\d+ np_edge_26_2

SELECT edge_build(0::int8, graph.id, label.id, 0::smallint, vertex_in('{}'), vertex_in('{}'))
FROM np_edge_label_26 label, np_graph graph
WHERE graph.name = 'edge_graph'
  AND label.ltree @ 'person';

SELECT create_elabel('edge_graph', 'person.employee.engineer');

SELECT edge_build(1::int8, graph.id, label.id, 0::smallint, vertex_in('{}'), vertex_in('{}'))
FROM np_edge_label_26 label, np_graph graph
WHERE graph.name = 'edge_graph'
  AND label.ltree @ 'person';

--
-- Multi-Label Edge DDL & Migration Tests
--

-- 1. Setup: Create a vertex label
SELECT create_vlabel('edge_graph', 'node');

-- Insert Vertices explicitly using nextval
SELECT insert_vertex(vertex_build(nextval('np_vertex_id_seq_31_2')::int8, 31, 2, 0::smallint), '{}'::gtype);
SELECT insert_vertex(vertex_build(nextval('np_vertex_id_seq_31_2')::int8, 31, 2, 0::smallint), '{}'::gtype);

-- 2. Setup: Base edge labels (These become 4 and 5)
SELECT create_elabel('edge_graph', 'colleague');
SELECT create_elabel('edge_graph', 'manager');

-- 3. Test: merge_elabels (Manual LTREE path concatenation)
SELECT merge_elabels('edge_graph', 4, 5);

-- Verify the merged label exists in the catalog
SELECT id, ltree FROM np_edge_label_31 WHERE ltree = '_.colleague.manager'::ltree;

-- 4. Setup: Insert edge 1 between Vertex 1 and Vertex 2
SELECT insert_edge(vertex_build(1::int8, 31, 2, 0::smallint), vertex_build(2::int8, 31, 2, 0::smallint), edge_build(nextval('np_edge_id_seq_31_4')::int8, 31, 4, 0::smallint, vertex_build(1::int8, 31, 2, 0::smallint), vertex_build(2::int8, 31, 2, 0::smallint)), '{"department": "engineering"}'::gtype);

SELECT * FROM np_edge_31_4;

-- 5. Test: set_edge_label (The Migration Engine)
SELECT set_edge_label(1::int8, 4, 31, 'promoted'::text);

-- Verify the new label was auto-generated by the migrator
SELECT id, ltree FROM np_edge_label_31 WHERE ltree = '_.colleague.promoted'::ltree;

-- 6. Test: remove_edge_label
-- Downgrades Edge 1 from '_.colleague.promoted' (ID 8) back to '_.colleague' (ID 4)
SELECT remove_edge_label(1::int8, 8, 31, 'promoted'::text);

-- Verify it properly migrated back to the original table
SELECT * FROM np_edge_31_4 WHERE id = 1;

--
-- Edge Annotations Tests
--

-- 1. Create a new edge label equipped with an annotation schema
SELECT create_elabel('edge_graph', 'friend', 'public', ARRAY['close', 'distant']);

-- 2. Insert a new edge (Edge ID 2, Label ID 9) between Vertex 1 and 2
SELECT insert_edge(vertex_build(1::int8, 31, 2, 0::smallint), vertex_build(2::int8, 31, 2, 0::smallint), edge_build(2::int8, 31, 9, 0::smallint, vertex_build(1::int8, 31, 2, 0::smallint), vertex_build(2::int8, 31, 2, 0::smallint)), '{"met": "college"}'::gtype);

-- 3. Initial State: Output should show base label "friend"
SELECT * FROM np_edge_31_9 WHERE id = 2;

-- 4. Mutation: Add the 'close' annotation
SELECT add_edge_annotation(2::int8, 9, 31, 'close');

-- 4a. Prove Binary State: Entity Store should hold the updated bitset
SELECT id, annotations FROM np_edge_annotations_31_9 WHERE id = 2;

-- 4b. Prove String State: edge_out should dynamically append ":close"
SELECT * FROM np_edge_31_9 WHERE id = 2;

-- 5. Teardown: Remove the 'close' annotation
SELECT remove_edge_annotation(2::int8, 9, 31, 'close');

-- 5a. Prove Binary State: Entity Store bitset should revert
SELECT id, annotations FROM np_edge_annotations_31_9 WHERE id = 2;

-- 5b. Prove String State: edge_out should revert to base label "friend"
SELECT * FROM np_edge_31_9 WHERE id = 2;

--
-- Schema DDL: add_annotation_label on edge structural labels
-- Cascades to every catalog row under the structural path, including
-- is_primary = false partitions. Creates annotations_tbl when missing.
--
SELECT add_annotation_label('edge_graph', 'friend', 'bestie');
SELECT id, ltree, annotation_map, is_primary FROM np_edge_label_31 WHERE id = 9;

SELECT add_edge_annotation(2::int8, 9, 31, 'bestie');
SELECT id, annotations FROM np_edge_annotations_31_9 WHERE id = 2;
SELECT * FROM np_edge_31_9 WHERE id = 2;

SELECT add_annotation_label('edge_graph', 'colleague', 'former');
SELECT id, ltree, annotations_tbl IS NOT NULL AS has_annot_tbl, annotation_map, is_primary
FROM np_edge_label_31
WHERE ltree = '_.colleague'::ltree OR ltree ~ '*.colleague.*'::lquery
ORDER BY id;

SELECT drop_annotation_label('edge_graph', 'friend', 'bestie');
SELECT id, ltree, annotation_map, is_primary FROM np_edge_label_31 WHERE id = 9;

SELECT drop_annotation_label('edge_graph', 'colleague', 'former');
SELECT id, ltree, annotation_map, is_primary
FROM np_edge_label_31
WHERE ltree = '_.colleague'::ltree OR ltree ~ '*.colleague.*'::lquery
ORDER BY id;

-- =====================================================================
-- TEST: drop_elabel (O(1) Metadata-Only Migration)
-- =====================================================================

SELECT create_graph('drop_elabel_graph', 'public');

-- 1. Setup Label Hierarchy: _.knows.works_with.reports_to
SELECT create_elabel('drop_elabel_graph', 'knows');
SELECT create_elabel('drop_elabel_graph', 'works_with');
SELECT create_elabel('drop_elabel_graph', 'reports_to');

-- Assuming IDs: root=1, knows=2, works_with=3, reports_to=4
SELECT merge_elabels('drop_elabel_graph', 2, 3); -- Creates _.knows.works_with (ID=5)
SELECT merge_elabels('drop_elabel_graph', 5, 4); -- Creates _.knows.works_with.reports_to (ID=6)

-- Vertices so we can store edges in the partitions
SELECT create_vlabel('drop_elabel_graph', 'node');
SELECT insert_vertex(vertex_build(nextval('np_vertex_id_seq_32_2')::int8, 32, 2, 0::smallint), '{"name": "A"}'::gtype);
SELECT insert_vertex(vertex_build(nextval('np_vertex_id_seq_32_2')::int8, 32, 2, 0::smallint), '{"name": "B"}'::gtype);

-- Insert an edge into each structural partition that will be remapped
SELECT insert_edge(vertex_build(1::int8, 32, 2, 0::smallint), vertex_build(2::int8, 32, 2, 0::smallint), edge_build(nextval('np_edge_id_seq_32_2')::int8, 32, 2, 0::smallint, vertex_build(1::int8, 32, 2, 0::smallint), vertex_build(2::int8, 32, 2, 0::smallint)), '{"kind": "knows"}'::gtype);
SELECT insert_edge(vertex_build(1::int8, 32, 2, 0::smallint), vertex_build(2::int8, 32, 2, 0::smallint), edge_build(nextval('np_edge_id_seq_32_5')::int8, 32, 5, 0::smallint, vertex_build(1::int8, 32, 2, 0::smallint), vertex_build(2::int8, 32, 2, 0::smallint)), '{"kind": "works_with"}'::gtype);
SELECT insert_edge(vertex_build(1::int8, 32, 2, 0::smallint), vertex_build(2::int8, 32, 2, 0::smallint), edge_build(nextval('np_edge_id_seq_32_6')::int8, 32, 6, 0::smallint, vertex_build(1::int8, 32, 2, 0::smallint), vertex_build(2::int8, 32, 2, 0::smallint)), '{"kind": "reports_to"}'::gtype);

-- Verify initial catalog state
SELECT id, ltree, tbl, is_primary FROM np_edge_label_32 ORDER BY id;

-- =====================================================================
-- SCENARIO A: Drop a leaf label ('reports_to')
-- Expected: reports_to edge STAYS in Table 6, but Table 6 is logically remapped
-- =====================================================================
SELECT drop_elabel('drop_elabel_graph', 'reports_to');

-- Verify catalog:
-- ID 4 (_.reports_to) becomes _ with is_primary = f
-- ID 6 (_.knows.works_with.reports_to) becomes _.knows.works_with with is_primary = f
SELECT id, ltree, tbl, is_primary FROM np_edge_label_32 ORDER BY id;

-- Verify O(1) Storage: payload must STILL live in its original physical table
SELECT id, edge FROM np_edge_32_6 ORDER BY id;

-- =====================================================================
-- SCENARIO B: Drop an intermediate label ('works_with')
-- Expected: both works_with and reports_to partitions logically shift to _.knows
-- =====================================================================
SELECT drop_elabel('drop_elabel_graph', 'works_with');

-- Verify catalog:
-- ID 3 (_.works_with) becomes _ with is_primary = f
-- ID 5 (_.knows.works_with) becomes _.knows with is_primary = f
-- ID 6 (was _.knows.works_with) becomes _.knows with is_primary = f
SELECT id, ltree, tbl, is_primary FROM np_edge_label_32 ORDER BY id;

SELECT id, edge FROM np_edge_32_5 ORDER BY id;
SELECT id, edge FROM np_edge_32_6 ORDER BY id;

-- =====================================================================
-- SCENARIO C: Drop the base label ('knows')
-- Expected: all remapped partitions fallback to root '_'
-- =====================================================================
SELECT drop_elabel('drop_elabel_graph', 'knows');

SELECT id, ltree, tbl, is_primary FROM np_edge_label_32 ORDER BY id;

SELECT id, edge FROM np_edge_32_2 ORDER BY id;
SELECT id, edge FROM np_edge_32_5 ORDER BY id;
SELECT id, edge FROM np_edge_32_6 ORDER BY id;