/*
 * Copyright (C) 2026 PostGraphDB
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
LOAD 'neopostgraph';

SET search_path TO public, pg_catalog, NeoPostGraph;

SELECT FROM edge_in('{"name": "Alice", "age": 30}');

SELECT edge_in('{"name": "Alice", "age": 30}');
SELECT * FROM edge_in('{"name": "Alice", "age": 30}');

--
-- Edge Input Routine
-- NOTE: Never going to be used
--
SELECT edge_in('{}');
SELECT edge_in('{"name": "Alice", "age": 30}');
SELECT edge_in('{"nested": {"a": 1, "b": [2, 3]}}');
SELECT edge_in('{"bool": true, "nullval": null, "float": 3.14}');
SELECT edge_in('{"name": "Bob", "tags": ["dev", "graph"], "scores": [95, 87, 92], "active": true}');

--
-- Edge basic constructor
--
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'),'{}'::gtype);
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'),'{"name": "Alice", "age": 30}'::gtype);
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'),'{"nested": {"a": 1, "b": [2, 3]}}'::gtype);
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'),'{"bool": true, "nullval": null, "float": 3.14}'::gtype);
SELECT edge_build(0::int8, 0, 0, 0::smallint, vertex_in('{}'), vertex_in('{}'),'{"name": "Bob", "tags": ["dev", "graph"], "scores": [95, 87, 92], "active": true}'::gtype);

--
-- Vertex LTree Label Logic
--
SELECT create_graph('edge_graph', 'public');
SELECT create_elabel('edge_graph', 'person');

SELECT * FROM np_graph graph WHERE graph.name = 'edge_graph';
select * FROM np_edge_label_26;

\d+ np_edge_label_26
\d+ np_edge_26_2

SELECT edge_build(0::int8, graph.id, label.id, 0::smallint, vertex_in('{}'), vertex_in('{}'),'{"name": "Bob", "tags": ["dev", "graph"], "scores": [95, 87, 92], "active": true}'::gtype)
FROM np_edge_label_26 label, np_graph graph
WHERE graph.name = 'edge_graph'
  AND label.ltree @ 'person';

SELECT create_elabel('edge_graph', 'person.employee.engineer');

SELECT edge_build(1::int8, graph.id, label.id, 0::smallint,vertex_in('{}'), vertex_in('{}'),'{"name": "Alice", "age": 30}'::gtype)
FROM np_edge_label_26 label, np_graph graph
WHERE graph.name = 'edge_graph'
  AND label.ltree @ 'person';

--
-- Multi-Label Edge DDL & Migration Tests
--

-- 1. Setup: Create a vertex label
SELECT create_vlabel('edge_graph', 'node');

-- Insert Vertices explicitly using nextval
SELECT insert_vertex(vertex_build(nextval('np_vertex_id_seq_31_2')::int8, 31, 2, 0::smallint, '{}'::gtype));
SELECT insert_vertex(vertex_build(nextval('np_vertex_id_seq_31_2')::int8, 31, 2, 0::smallint, '{}'::gtype));

-- 2. Setup: Base edge labels (These become 4 and 5)
SELECT create_elabel('edge_graph', 'colleague');
SELECT create_elabel('edge_graph', 'manager');

-- 3. Test: merge_elabels (Manual LTREE path concatenation)
SELECT merge_elabels('edge_graph', 4, 5);

-- Verify the merged label exists in the catalog
SELECT id, ltree FROM np_edge_label_31 WHERE ltree = '_.colleague.manager'::ltree;

-- 4. Setup: Insert edge 1 between Vertex 1 and Vertex 2
SELECT insert_edge(
    vertex_build(1::int8, 31, 2, 0::smallint, '{}'::gtype),
    vertex_build(2::int8, 31, 2, 0::smallint, '{}'::gtype),
    edge_build(nextval('np_edge_id_seq_31_4')::int8, 31, 4, 0::smallint, 
        vertex_build(1::int8, 31, 2, 0::smallint, '{}'::gtype),
        vertex_build(2::int8, 31, 2, 0::smallint, '{}'::gtype),
        '{"department": "engineering"}'::gtype
    )
);

SELECT * FROM np_edge_31_4;

-- 5. Test: set_edge_label (The Migration Engine)
SELECT set_edge_label(1::int8, 4, 31, 'promoted'::text);

-- Verify the new label was auto-generated by the migrator
SELECT id, ltree FROM np_edge_label_31 WHERE ltree = '_.colleague.promoted'::ltree;

-- 6. Test: remove_edge_label
-- Downgrades Edge 1 from '_.colleague.promoted' (ID 8) back to '_.colleague' (ID 4)
SELECT remove_edge_label(1::int8, 8, 31, 'promoted'::text);

-- Verify it properly migrated back to the original table
SELECT * FROM np_edge_31_4 WHERE id = 1;